package com.tsquaredapplications.liquid.common.database

const val PREFS_FILE = "prefsFile"
const val WEIGHT = "weight"
const val DAILY_GOAL = "dailyGoal"
const val UNIT_PREFERENCE = "unitPreference"
const val SHOULD_SHOW_ALCOHOL_WARNING = "shouldShowAlcoholWarning"
const val NOTIFICATIONS_ENABLED = "NOTIFICATIONS_ENABLED"
const val NOTIFICATION_START_TIME_HOUR = "NOTIFICATION_START_TIME_HOUR"
const val NOTIFICATION_START_TIME_MIN = "NOTIFICATION_START_TIME_MIN"
const val NOTIFICATION_END_TIME_HOUR = "NOTIFICATION_END_TIME_HOUR"
const val NOTIFICATION_END_TME_MIN = "NOTIFICATION_END_TME_MIN"
const val NOTIFICATION_INTERVAL_MINS = "NOTIFICATION_INTERVAL_MINS"

const val ONBOARDING_NOTIFICATION_SETUP_PERFORMED = "ONBOARDING_NOTIFICATION_SETUP_PERFORMED"